#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo -e "\e[41mзапусти от суперпользователя.\e[0m"
  exit 1
fi

source /etc/os-release
OS_VERSION="$VERSION_ID"

TMP_DIR=$(mktemp -d)
REPO="https://github.com/UzbekLinux/uzfiles.git"

echo "загрузка файлов для версии $BRANCH..."
git clone --depth 1 --branch "$BRANCH" "$REPO" "$TMP_DIR"

echo "файлы скачаны с репо ($BRANCH)"

TREE_DIR="$TMP_DIR/$COPY_DIR"
if [[ ! -d "$TREE_DIR" ]]; then
  echo -e "\e[41mнет папки $COPY_DIR в репо!\e[0m"
  exit 1
fi

echo "копирую $COPY_DIR в корень..."
if mount | grep -q "iso9660"; then
    cp -rf "$TMP_DIR/live-tree/"* /
else
    cp -rf "$TMP_DIR/tree/"* /
fi

if [[ -f /tmp/update.sh ]]; then
    chmod +x /tmp/update.sh
    sh /tmp/update.sh
else
    echo -e "\e[41m/tmp/update.sh не найден!\e[0m"
fi

rm -rf "$TMP_DIR"
echo
echo "готово."
