#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo -e "\e[41mзапусти от суперпользователя.\e[0m"
  exit 1
fi

TMP_SCRIPT="/tmp/uzupdate"
if [[ -f /usr/local/bin/uzupdate ]]; then
    cp -f /usr/local/bin/uzupdate "$TMP_SCRIPT"
    chmod +x "$TMP_SCRIPT"
    if [[ "$(readlink -f "$0")" != "$TMP_SCRIPT" ]]; then
        exec "$TMP_SCRIPT" "$@"
    fi
else
    echo -e "\e[41m/usr/local/bin/uzupdate не найден!\e[0m"
    exit 1
fi

source /etc/os-release
BRANCH="$VERSION_ID"

TMP_DIR=$(mktemp -d)
REPO="https://github.com/UzbekLinux/uzfiles.git"

echo "загрузка файлов для версии $BRANCH..."
git clone --depth 1 --branch "$BRANCH" "$REPO" "$TMP_DIR" || {
    if command -v notify-send >/dev/null 2>&1; then
        notify-send --urgency=critical \
            "Ошибка Uzbek Linux" \
            "произошла ошибка обновления системы! подключись к интернету."
    fi
    echo -e "\e[41mпроизошла ошибка обновления системы! подключись к интернету.\e[0m"
    exit 1
}
echo "файлы скачаны с репо ($BRANCH)"

if [[ -d /run/archiso ]]; then
    cp -rfv "$TMP_DIR/live-tree/"* /
else
    cp -rfv "$TMP_DIR/tree/"* /
fi


if [[ -f /tmp/update.sh ]]; then
    chmod +x /tmp/update.sh
    sh /tmp/update.sh
else
    echo -e "\e[41m/tmp/update.sh не найден!\e[0m"
fi

rm -rf "$TMP_DIR"
echo
echo "готово."
